config/routes.rb
GmailDb::Application.routes.draw do
  root to: 'admin#index', constraints: lambda { |r| r.env['warden'].authenticate? }, as: :admin
  root 'home#index'
  devise_for :admins

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :interactions, dependent: :destroy
  has_many :gmail_messages

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :employees
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :company
  has_many :interactions, dependent: :destroy

end

app/models/gmail_message.rb
class GmailMessage < ActiveRecord::Base
  has_many :parts
  belongs_to :admin

  scope :sent_by, ->(user){ where(from: user.email) }

  def body
    parts.select{|part| part.content.include?("MIME-Version: 1.0")}[0].content
  end
end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
  belongs_to :employee
  belongs_to :admin

  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :interaction
  has_many   :parts, dependent: :destroy
end

app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :gmail_message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u|
      u.permit(:username, :email, :password,
               :password_confirmation, :gmail_password)
    }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="form_wrapper">
  <%= link_to "Become an Admin", new_admin_registration_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GmailDb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>